# Multi-stage Nginx Frontend Dockerfile
FROM node:20-alpine as build

WORKDIR /app

COPY frontend/package*.json ./
COPY frontend/.npmrc ./

RUN npm install

COPY frontend ./

RUN npm run build

# Stage 2: Nginx Web Server
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
